# Generated by Django 4.1.6 on 2023-09-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='creditcard',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
