# Generated by Django 4.2.7 on 2023-11-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_address_alter_profile_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='creditcard',
            field=models.IntegerField(blank=True, null=True, verbose_name='creditcard'),
        ),
    ]
