# Generated by Django 4.1 on 2023-09-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('maker', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2048)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('associated_furnitures', models.ManyToManyField(blank=True, to='main.furniture')),
            ],
        ),
    ]
