# Generated by Django 4.1 on 2023-09-10 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='associated_furnitures',
        ),
    ]
