# Generated by Django 4.2.7 on 2023-11-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='associated_furnitures',
            field=models.ManyToManyField(blank=True, related_name='associated_fornitures', to='main.furniture'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='description',
            field=models.CharField(max_length=2048, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='maker',
            field=models.CharField(max_length=255, verbose_name='maker'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='material',
            field=models.CharField(max_length=255, verbose_name='material'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='type',
            field=models.CharField(max_length=255, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=100, verbose_name='content'),
        ),
    ]
