# Generated by Django 4.1 on 2023-09-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_furniture_associated_furnitures'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='associated_furnitures',
            field=models.ManyToManyField(blank=True, to='main.furniture'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='image_url',
            field=models.URLField(default='https://superficiescubik.com/wp-content/uploads/2018/12/cubik-icono-muebles.png'),
            preserve_default=False,
        ),
    ]
